/*
 * SPDX-FileCopyrightText: 2022 The HedgeDoc developers (see AUTHORS file)
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */
import WebSocket from 'ws';

import { RealtimeNote } from './realtime-note';
import {
  encodeAwarenessMessage,
  encodeInitialSyncMessage,
} from './yjs-messages';

export class WebsocketConnection {
  private pongReceived = true;
  private readonly pingTimeout = 30 * 1000;

  constructor(
    private websocket: WebSocket,
    private realtimeNote: RealtimeNote,
  ) {
    this.setupPing();
    this.sendInitialSync();
    this.sendAwarenessState();
  }

  private setupPing(): void {
    const pingInterval = setInterval(() => {
      if (this.pongReceived) {
        this.pongReceived = false;
        try {
          this.websocket.ping();
        } catch (e) {
          this.websocket.close();
        }
      } else {
        this.websocket.close();
      }
    }, this.pingTimeout);
    this.websocket.on('close', () => {
      clearInterval(pingInterval);
    });
    this.websocket.on('pong', () => {
      this.pongReceived = true;
    });
  }

  /**
   * Send the data generated by writeSyncStep1 to the client.
   *
   * This initializes the client and sends the current note content.
   */
  public sendInitialSync(): void {
    this.send(encodeInitialSyncMessage(this.realtimeNote.getYDoc()));
  }

  public sendAwarenessState(): void {
    this.send(encodeAwarenessMessage(this.realtimeNote.getAwareness()));
  }

  public send(content: Uint8Array): void {
    if (this.websocket.readyState !== WebSocket.OPEN) {
      return;
    }

    try {
      this.websocket.send(content);
    } catch (error: unknown) {
      this.websocket.close();
    }
  }
}
